import type { CodeGraph, GraphNodeV2 } from "../domain/code-graph.ts";
import { overviewGraphHealth, architectureGraphSummary } from "./repository-graph-view.ts";

function v2(graph: CodeGraph) {
  return graph.schemaVersion === "2.0" ? graph : null;
}

function sanitizeId(id: string): string {
  return "n_" + id.replace(/[^a-zA-Z0-9_]/g, "_");
}

function escapeMermaid(text: string): string {
  return text.replace(/["\\]/g, "\\$&").replace(/\n/g, " ");
}

export function codeGraphToMermaid(graph: CodeGraph, maxEdges = 50): string {
  const current = graph && v2(graph);
  if (!current) return "graph TD\n  empty[Empty or invalid graph]";

  const lines: string[] = ["graph TD"];
  const nodeMap = new Map<string, GraphNodeV2>(current.nodes.map((n) => [n.id, n]));
  const usedNodes = new Set<string>();

  // Filter significant edges (imports, calls, handles-route, inherits)
  const edges = current.edges
    .filter((e) => e.kind !== "contains" && e.kind !== "declares")
    .slice(0, maxEdges)
    .sort((a, b) => (a.from + a.to + a.kind).localeCompare(b.from + b.to + b.kind));

  for (const e of edges) {
    const fromNode = nodeMap.get(e.from);
    const toNode = nodeMap.get(e.to);
    if (!fromNode || !toNode) continue;

    const fromId = sanitizeId(fromNode.id);
    const toId = sanitizeId(toNode.id);

    if (!usedNodes.has(fromNode.id)) {
      lines.push(`  ${fromId}["${escapeMermaid(fromNode.name)} (${fromNode.kind})"]`);
      usedNodes.add(fromNode.id);
    }
    if (!usedNodes.has(toNode.id)) {
      lines.push(`  ${toId}["${escapeMermaid(toNode.name)} (${toNode.kind})"]`);
      usedNodes.add(toNode.id);
    }

    const arrow = e.kind === "calls" ? "-->" : e.kind === "imports" ? "-.->" : "==>";
    lines.push(`  ${fromId} ${arrow}|"${e.kind}"| ${toId}`);
  }

  if (lines.length === 1) {
    lines.push("  no_edges[No structural relationships found]");
  }

  return lines.join("\n");
}

export function codeGraphToReport(graph: CodeGraph): string {
  const current = graph && v2(graph);
  if (!current) return "# CodeGraph Analysis Report\n\nNo graph available.";

  const health = overviewGraphHealth(current);
  const arch = architectureGraphSummary(current);
  const mermaid = codeGraphToMermaid(current, 30);

  const lines: string[] = [
    `# CodeGraph Analysis Report`,
    ``,
    `**Repository:** \`${current.snapshot.repository.owner}/${current.snapshot.repository.name}\``,
    `**Commit:** \`${current.snapshot.commitSha}\``,
    `**Schema:** \`v${current.schemaVersion}\``,
    health
      ? `**Health Score:** \`${health.score}/100\` (${health.coverage.analyzedFiles} analyzed, ${health.coverage.skippedFiles} skipped)`
      : "",
    ``,
    `## Summary Metrics`,
    ``,
    `- **Files:** ${current.metrics.files}`,
    `- **Symbols:** ${current.metrics.symbols}`,
    `- **Routes:** ${current.metrics.routes}`,
    `- **Packages:** ${current.metrics.packages}`,
    `- **Total Edges:** ${current.edges.length}`,
    ``,
    `## Hub Modules`,
    ``,
    ...(arch.hubs.length
      ? arch.hubs.map(
          (h) => `- \`${h.path}\` (${h.total} connections: ${h.fanIn} in / ${h.fanOut} out)`,
        )
      : ["- No hub modules detected."]),
    ``,
    `## Dependency Architecture`,
    ``,
    `\`\`\`mermaid`,
    mermaid,
    `\`\`\``,
    ``,
    `---`,
    `*Generated by RepoCompass CodeGraph Engine*`,
  ];

  return lines.filter(Boolean).join("\n");
}

export function codeGraphToHtml(graph: CodeGraph): string {
  const current = graph && v2(graph);
  if (!current)
    return '<!DOCTYPE html><html lang="en"><body><h1>No graph data available</h1></body></html>';

  const jsonString = JSON.stringify(current, null, 2);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CodeGraph - ${current.snapshot.repository.name}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: 20px; background: #0f172a; color: #f8fafc; }
    h1, h2 { border-bottom: 1px solid #334155; padding-bottom: 8px; }
    .card { background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #334155; }
    th { background: #0f172a; }
    code { background: #0f172a; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; background: #3b82f6; color: white; }
  </style>
</head>
<body>
  <h1>CodeGraph Report &mdash; ${current.snapshot.repository.owner}/${current.snapshot.repository.name}</h1>
  <div class="card">
    <h2>Snapshot Information</h2>
    <p><strong>Commit:</strong> <code>${current.snapshot.commitSha}</code></p>
    <p><strong>Files:</strong> ${current.metrics.files} | <strong>Symbols:</strong> ${current.metrics.symbols} | <strong>Edges:</strong> ${current.edges.length}</p>
  </div>
  <div class="card">
    <h2>Nodes (${current.nodes.length})</h2>
    <table>
      <thead><tr><th>Name</th><th>Kind</th><th>Location</th></tr></thead>
      <tbody>
        ${current.nodes
          .slice(0, 100)
          .map(
            (n) =>
              `<tr><td><code>${escapeMermaid(n.name)}</code></td><td><span class="badge">${n.kind}</span></td><td>${n.location?.path || "-"}</td></tr>`,
          )
          .join("")}
      </tbody>
    </table>
  </div>
  <script type="application/json" id="graph-data">${jsonString}</script>
</body>
</html>`;
}
